"""NUT config file generation and reading."""

from __future__ import annotations

import shutil
import time
from pathlib import Path
from typing import Any

HEADER = "# Generated by nut-up -- do not edit manually\n\n"

CONFIG_FILES = ["nut.conf", "ups.conf", "upsd.conf", "upsd.users", "upsmon.conf"]


class NUTConfigWriter:
    """Writes NUT configuration files."""

    def __init__(self, conf_dir: str = "/etc/nut") -> None:
        self.conf_dir = Path(conf_dir)

    def _write(self, filename: str, content: str) -> Path:
        """Create the config directory if needed and write HEADER + content."""
        self.conf_dir.mkdir(parents=True, exist_ok=True)
        path = self.conf_dir / filename
        path.write_text(HEADER + content, encoding="utf-8")
        return path

    def backup_existing(self) -> list[str]:
        """Backup each existing config file to .bak.{timestamp}. Returns list of backup paths."""
        timestamp = str(int(time.time()))
        backups: list[str] = []
        for name in CONFIG_FILES:
            src = self.conf_dir / name
            if src.exists():
                dest = self.conf_dir / f"{name}.bak.{timestamp}"
                shutil.copy2(str(src), str(dest))
                backups.append(str(dest))
        return backups

    def write_nut_conf(self, mode: str) -> Path:
        """Write nut.conf with the given mode."""
        return self._write("nut.conf", f"MODE={mode}\n")

    def write_ups_conf(self, ups_list: list[dict[str, Any]]) -> Path:
        """Write ups.conf with INI-style sections for each UPS.

        Each dict should have: name, driver, port, desc, and optionally extra (dict).
        """
        lines: list[str] = []
        for ups in ups_list:
            lines.append(f"[{ups['name']}]")
            lines.append(f"    driver = {ups['driver']}")
            lines.append(f"    port = {ups['port']}")
            lines.append(f'    desc = "{ups["desc"]}"')
            for key, value in ups.get("extra", {}).items():
                lines.append(f'    {key} = "{value}"')
            lines.append("")
        return self._write("ups.conf", "\n".join(lines))

    def write_upsd_conf(self, listen_addresses: list[str], port: int = 3493) -> Path:
        """Write upsd.conf with LISTEN directives and MAXAGE."""
        lines: list[str] = []
        for addr in listen_addresses:
            lines.append(f"LISTEN {addr} {port}")
        lines.append("MAXAGE 15")
        lines.append("")
        return self._write("upsd.conf", "\n".join(lines))

    def write_upsd_users(self, admin_password: str, monitor_password: str) -> Path:
        """Write upsd.users with admin, primary, and secondary monitor users."""
        content = f"""\
[admin]
    password = {admin_password}
    actions = SET FSD
    instcmds = ALL

[upsmon_primary]
    password = {monitor_password}
    upsmon primary

[upsmon_secondary]
    password = {monitor_password}
    upsmon secondary
"""
        return self._write("upsd.users", content)

    def write_upsmon_conf(self, monitors: list[dict[str, Any]]) -> Path:
        """Write upsmon.conf with MONITOR lines and standard directives.

        Each monitor dict should have: ups_name, host (default localhost),
        port (default 3493), powervalue (default 1), user, password, role (primary/secondary).
        """
        lines: list[str] = []
        for mon in monitors:
            ups_name = mon["ups_name"]
            host = mon.get("host", "localhost")
            port = mon.get("port", 3493)
            powervalue = mon.get("powervalue", 1)
            user = mon["user"]
            password = mon["password"]
            role = mon["role"]
            lines.append(f"MONITOR {ups_name}@{host}:{port} {powervalue} {user} {password} {role}")

        lines.append("")
        lines.append("MINSUPPLIES 1")
        lines.append('SHUTDOWNCMD "/sbin/shutdown -h +0"')
        lines.append("POWERDOWNFLAG /etc/killpower")
        lines.append("POLLFREQ 5")
        lines.append("DEADTIME 15")
        lines.append("")
        lines.append('NOTIFYMSG ONLINE "UPS %s on line power"')
        lines.append('NOTIFYMSG ONBATT "UPS %s on battery!"')
        lines.append('NOTIFYMSG LOWBATT "UPS %s battery is low!"')
        lines.append('NOTIFYMSG FSD "UPS %s: forced shutdown in progress"')
        lines.append('NOTIFYMSG SHUTDOWN "Auto logout and target. Have a nice day."')
        lines.append("")
        lines.append("NOTIFYFLAG ONLINE SYSLOG+WALL")
        lines.append("NOTIFYFLAG ONBATT SYSLOG+WALL")
        lines.append("NOTIFYFLAG LOWBATT SYSLOG+WALL")
        lines.append("NOTIFYFLAG FSD SYSLOG+WALL")
        lines.append("NOTIFYFLAG SHUTDOWN SYSLOG+WALL")
        lines.append("")
        return self._write("upsmon.conf", "\n".join(lines))

    def write_server(
        self,
        mode: str,
        ups_list: list[dict[str, Any]],
        admin_password: str,
        monitor_password: str,
        listen_addresses: list[str] | None = None,
    ) -> list[Path]:
        """Write all 5 config files for a server setup.

        Default listen addresses: 0.0.0.0 for netserver, 127.0.0.1 for standalone.
        """
        if listen_addresses is None:
            listen_addresses = ["0.0.0.0"] if mode == "netserver" else ["127.0.0.1"]

        paths: list[Path] = []
        paths.append(self.write_nut_conf(mode))
        paths.append(self.write_ups_conf(ups_list))
        paths.append(self.write_upsd_conf(listen_addresses))
        paths.append(self.write_upsd_users(admin_password, monitor_password))

        monitors = [
            {
                "ups_name": ups["name"],
                "user": "upsmon_primary",
                "password": monitor_password,
                "role": "primary",
            }
            for ups in ups_list
        ]
        paths.append(self.write_upsmon_conf(monitors))
        return paths


class NUTConfigReader:
    """Reads existing NUT configuration."""

    def __init__(self, conf_dir: str = "/etc/nut") -> None:
        self.conf_dir = Path(conf_dir)

    def read_mode(self) -> str | None:
        """Parse nut.conf for MODE= line. Returns the mode or None if not found."""
        nut_conf = self.conf_dir / "nut.conf"
        if not nut_conf.exists():
            return None
        for line in nut_conf.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped.startswith("MODE="):
                return stripped.split("=", 1)[1].strip()
        return None

    def has_existing_config(self) -> bool:
        """Check if nut.conf or ups.conf already exists."""
        return (self.conf_dir / "nut.conf").exists() or (self.conf_dir / "ups.conf").exists()
