"""Human-readable descriptions for NUT variables and commands.

NUT's GET DESC / GET CMDDESC often return empty or unhelpful strings.
This module provides fallback descriptions for the most common ones.
"""

VARIABLES: dict[str, str] = {
    # Battery
    "battery.charge": "Current battery charge level",
    "battery.charge.low": "Threshold at which UPS signals low battery (triggers shutdown)",
    "battery.charge.warning": "Threshold for battery warning notifications",
    "battery.runtime": "Estimated seconds of runtime remaining on battery",
    "battery.runtime.low": "Minimum runtime before UPS signals low battery",
    "battery.runtime.nominal": "Nominal battery runtime at full charge and zero load",
    "battery.voltage": "Current battery voltage",
    "battery.voltage.nominal": "Nominal battery voltage",
    "battery.type": "Battery chemistry type (PbAc, Li-ion, etc.)",
    "battery.date": "Date the battery was last replaced",
    "battery.mfr.date": "Battery manufacture date",
    "battery.packs": "Number of battery packs",
    "battery.packs.bad": "Number of bad battery packs",
    "battery.temperature": "Battery temperature in Celsius",
    # Input
    "input.voltage": "Current input (mains) voltage",
    "input.voltage.nominal": "Nominal input voltage (expected from mains)",
    "input.voltage.maximum": "Maximum input voltage seen",
    "input.voltage.minimum": "Minimum input voltage seen",
    "input.transfer.high": "High voltage threshold — above this, UPS switches to battery",
    "input.transfer.low": "Low voltage threshold — below this, UPS switches to battery",
    "input.transfer.reason": "Reason for last transfer to battery",
    "input.sensitivity": "Input voltage sensitivity (H=high, M=medium, L=low)",
    "input.frequency": "Current input frequency in Hz",
    "input.frequency.nominal": "Nominal input frequency",
    # Output
    "output.voltage": "Current output voltage supplied to equipment",
    "output.voltage.nominal": "Nominal output voltage",
    "output.current": "Current output current in amps",
    "output.current.nominal": "Nominal output current capacity",
    "output.frequency": "Current output frequency in Hz",
    "output.frequency.nominal": "Nominal output frequency",
    # UPS
    "ups.status": "UPS status flags (OL=online, OB=on battery, LB=low battery, etc.)",
    "ups.load": "Current load as percentage of UPS capacity",
    "ups.power": "Current real power output in watts",
    "ups.power.nominal": "Nominal UPS power capacity in watts",
    "ups.realpower": "Current real power in watts",
    "ups.realpower.nominal": "Nominal real power capacity in watts",
    "ups.temperature": "Internal UPS temperature in Celsius",
    "ups.delay.shutdown": "Seconds to wait before shutting off power after FSD",
    "ups.delay.start": "Seconds to wait before restoring power after mains return",
    "ups.timer.shutdown": "Time until UPS shuts off (-1 = not started)",
    "ups.timer.start": "Time until UPS restores power (-1 = not started)",
    "ups.model": "UPS model name",
    "ups.mfr": "UPS manufacturer",
    "ups.mfr.date": "UPS manufacture date",
    "ups.serial": "UPS serial number",
    "ups.firmware": "UPS firmware version",
    "ups.firmware.aux": "Auxiliary firmware version",
    "ups.type": "UPS type (offline, line-interactive, online)",
    "ups.id": "UPS identifier string (user-configurable on some models)",
    "ups.beeper.status": "Beeper state (enabled, disabled, muted)",
    "ups.test.result": "Result of last self-test",
    "ups.test.date": "Date of last self-test",
    # Device
    "device.model": "Device model name",
    "device.mfr": "Device manufacturer",
    "device.serial": "Device serial number",
    "device.type": "Device type (ups, pdu, etc.)",
    # Driver
    "driver.name": "NUT driver name",
    "driver.version": "NUT driver version",
    "driver.version.internal": "Internal driver version",
    "driver.version.data": "Driver data version",
    "driver.parameter.pollinterval": "How often the driver polls the UPS (seconds)",
    "driver.parameter.pollfreq": "Alternative poll frequency setting",
}

COMMANDS: dict[str, str] = {
    "test.battery.start": "Start a battery self-test (typically 10 seconds)",
    "test.battery.start.quick": "Start a quick battery test",
    "test.battery.start.deep": "Start a deep battery test (runs until low battery)",
    "test.battery.stop": "Stop a running battery test",
    "test.panel.start": "Start a front panel LED/LCD test",
    "test.panel.stop": "Stop a front panel test",
    "beeper.toggle": "Toggle the UPS beeper on/off",
    "beeper.enable": "Enable the UPS beeper",
    "beeper.disable": "Disable the UPS beeper",
    "beeper.mute": "Temporarily mute the beeper (until next event)",
    "load.off": "Turn off power to the load immediately",
    "load.off.delay": "Turn off power after configured delay",
    "load.on": "Turn on power to the load immediately",
    "load.on.delay": "Turn on power after configured delay",
    "shutdown.return": "Shut down UPS and restart when mains return",
    "shutdown.stayoff": "Shut down UPS and stay off until manually restarted",
    "shutdown.stop": "Cancel a pending shutdown",
    "shutdown.reboot": "Reboot the UPS (power cycle the load)",
    "shutdown.reboot.graceful": "Graceful reboot — wait for delay, then power cycle",
    "calibrate.start": "Start a runtime calibration (drains battery to recalibrate)",
    "calibrate.stop": "Stop a runtime calibration",
    "bypass.start": "Switch to bypass mode (raw mains to load, no conditioning)",
    "bypass.stop": "Switch back from bypass to normal mode",
    "reset.input.minmax": "Reset recorded min/max input voltage values",
    "reset.watchdog": "Reset the UPS watchdog timer",
    "outlet.1.load.off": "Turn off outlet 1",
    "outlet.1.load.on": "Turn on outlet 1",
    "outlet.1.load.cycle": "Power cycle outlet 1",
    "outlet.2.load.off": "Turn off outlet 2",
    "outlet.2.load.on": "Turn on outlet 2",
    "outlet.2.load.cycle": "Power cycle outlet 2",
}
